ELN-0602 - Deployment Profile for the Swedish eID Framework.md, ELN-0604 - Attribute Specification for the Swedish eID Framework.md
The eidas connector needs to include enough information in its
assertion so that the SP knows which IdP (member state node) that
provided the authentication and which assertion that was issued.
=> IS-12 Requirements for Proxy-IdP:s

ELN-0603 - Registry for Identifiers.md, ELN-0607 - Implementation Profile for using DSS in Central Signing Services.md, versions.md
The status code http://id.elegnamnden.se/sig-status/1.0/user-cancel was
added. It is used to signal that a user has cancelled the
“authentication for signature”-process.
=> IS-13 Added cancel signature response status code

ELN-0602 - Deployment Profile for the Swedish eID Framework.md, Updates to the Swedish eID Framework.md, versions.md
Corrected section 6.3.4 of the Deployment profile with correct requirements for processing a received authentication context URI (LoA).
=> IS-34 Fixed bad requirement about authn context URI processing

ELN-0604 - Attribute Specification for the Swedish eID Framework.md, ELN-0606 - Entity Categories for the Swedish eID Framework.md
When a Swedish “samordningsnummer” (instead of a “personnummer”) is
delivered it may not be possible for the attribute consumer to deduce
the date of birth. This information is required when delivering
assertion within eIDAS.
=> IS-47 Added requirements for dateOfBirth attribute

ELN-0600 - Tekniskt ramverk - Svensk e-legitimation.md, ELN-0602 - Deployment Profile for the Swedish eID Framework.md, ELN-0606 - Entity Categories for the Swedish eID Framework.md
Added general requirement about how a SP wishing to make use of a
centralized discovery service according to IdpDisco should indicate
allowed response URLs.
Also cleaned up older text about discovery.
=> IS-55 Notes about discovery

ELN-0602 - Deployment Profile for the Swedish eID Framework.md, ELN-0603 - Registry for Identifiers.md
An update was made so that an SP may request authentication by a
particular IdP when sending an AuthnRequest to a Proxy IdP.
=> IS-57 Proxy IdP:s should support Scoping

ELN-0613 - Signature Activation Protocol.md, versions.md
The RequestedVersion element of the SADRequestType is now marked as
optional in the schema definition.
=> IS-60 Schema fix

ELN-0602 - Deployment Profile for the Swedish eID Framework.md
The deployment profile now references “SAML v2.0 Metadata Profile for
Algorithm Support Version 1.0”
(http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-metadata-alg
support.pdf).
=> IS-72 Added sections about md algorithm support

ELN-0603 - Registry for Identifiers.md
In section 3.1.1 of Swedish eID Framework - Registry for identifiers we list eIDAS URI:s for non-notified eID schemes as `http://eidas.europa.eu/LoA/NotNotified/low`, `http://eidas.europa.eu/LoA/NotNotified/substantial` and `http://eidas.europa.eu/LoA/NotNotified/high`.
According to eIDAS SAML Message Format v1.2 they should be:
`http://eidas.europa.eu/NotNotified/LoA/low`, `http://eidas.europa.eu/NotNotified/LoA/substantial`, and `http://eidas.europa.eu/NotNotified/LoA/high`.
=> IS-85 Fix for EU non-notified URI:s

ELN-0606 - Entity Categories for the Swedish eID Framework.md
If attribute release is in loa3-pnr scope, the personalIdentityNumber attribute may only hold a Swedish "personnummer" and not a "samordingsnummer".
=> IS-79 Added restriction about attribute release

ELN-0606 - Entity Categories for the Swedish eID Framework.md, ELN-0612 - BankID Profile for the Swedish eID Framework.md
Update to the BankID specification with definitions of how to announce required QR code support.
=> IS-84 QR code entity category for BankID use

ELN-0600 - Tekniskt ramverk - Introduktion.md, ELN-0602 - Deployment Profile for the Swedish eID Framework.md, ELN-0603 - Registry for Identifiers.md, ELN-0604 - Attribute Specification for the Swedish eID Framework.md, ELN-0607 - Implementation Profile for using DSS in Central Signing Services.md, ELN-0608 - Certificate Profile for Central Signing Services.md, ELN-0611 - eIDAS Constructed Attributes Specification for the Swedish eID Framework.md, ELN-0613 - Signature Activation Protocol.md, ELN-0614 - Principal Selection in SAML Authentication Requests.md, versions.md
Made sure to remove elegnämnden references and updated reference lists.
=> IS-50 Sweden Connect logo

ELN-0602 - Deployment Profile for the Swedish eID Framework.md, ELN-0612 - BankID Profile for the Swedish eID Framework.md, ELN-0614 - Principal Selection in SAML Authentication Requests.md
Added requirements that ensure that a sign message is not display to an unintended principal.
=> IS-99 Protect sign message

07 - Implementation Profile for using DSS in Central Signing Services.md, 09 - DSS Extension for Federated Signing Services.md
Reverted to 1.1 CSIG namespace for 1.1.2 draft.
Added clarifications on how to use Version attributes.
=> IS-129 Version handling

11 - eIDAS Constructed Attributes Specification for the Swedish eID Framework.md, versions.md
The length requirement for identifier characters has been changed from 8 to 6. This applies to the default-eIDAS and colresist-eIDAS algorithms.
=> IS-141 Changed length requirements for ID:s

07 - Implementation Profile for using DSS in Central Signing Services.md
Section 2.1.3.3, "Signer", was updated so that it is no longer required to supply a list of SAML attributes using the `<csig:Signer>` element. This enables use cases where the user is not known at the time of signature initiation.
Closes #127
=> IS-127 csig:Signer is not optional

02 - Deployment Profile for the Swedish eID Framework.md, 04 - Attribute Specification for the Swedish eID Framework.md
We added rules for "scoped attributes". Currently, this applies to the orgAffiliation attribute.
=> IS-153: Introduction of scoped attributes

03 - Registry for Identifiers.md, 06 - Entity Categories for the Swedish eID Framework.md
Added authentication context URIs for uncertified providers and for non-resident eID holders.
Also modified the definition of service entity categories allowing the official LoA URI as well as variants of it (uncertified, non-resident).
Closes #178
=> IS-178 Defined more authContext URIs and modified service categories

04 - Attribute Specification for the Swedish eID Framework.md, README.md
The personalIdentityNumberBinding can contain more than one URI identifying the binding processes applied to obtain an identity binding.
Closes #210
=> IS-210 Updates concerning the meaning of personalIdentityNumberBinding

Identity Binding.md
Updated version where the bindings for Nordic eID:s and relative confirmations were removed due to legal reasons.
=> IS-216 The bindings for Nordic eID:s and relative confirmations were removed due to legal reasons

.gitignore, OIDC - Sweden Connect - OpenID Connect Profile.md
@Razumain I would like to add a requirement for client metadata where its `organization` is given, but can not seem to find a standardized claim for this. Does OpenID Fed declare this?
This is a first draft, and we will add more stuff later on. In the comments add anything you think is missing for the first version.
=> IS-225 First draft of Sweden Connect OIDC Profile
