swedenconnect/technical-framework

ELN-0606 - Entity Categories for the Swedish eID Framework.md

Some major rewrites of service entity category to provide more distinct
definitions.

Suggested updates entity category

---

ELN-0606 - Entity Categories for the Swedish eID Framework.md

Fixed comments

---

ELN-0611 - eIDAS Constructed Attributes Specification for the Swedish eID Framework.md

Adds new algoritm for the case where the identifier received from the authenticating country is a Base64 value of some binary data.

New provisional ID algoritm

---

ELN-0603 - Registry for Identifiers.md

http://id.swedenconnect.se/ec/sc/uncertified-loa3-pnr was added to
registry of identifiers.

IS-74 Added service entity category uncertified-loa3-pnr

---

ELN-0612 - BankID Profile for the Swedish eID Framework.md
versions.md

Also updated reference to BankID API.

Changed recommendations for cancel

---

ELN-0600 - Swedish eID Framework - Introduction.md
ELN-0600 - Tekniskt ramverk - Introduktion.md
ELN-0602 - Deployment Profile for the Swedish eID Framework.md

Added section about cryptograhic algorithms.
Made old SAML2Int-requirements explicit.
Wrote about key rollover.

IS-75 Free standing from SAML2Int

---

ELN-0603 - Registry for Identifiers.md
ELN-0604 - Attribute Specification for the Swedish eID Framework.md
ELN-0606 - Entity Categories for the Swedish eID Framework.md

Attribute definition of HSA-ID attribute, along with attribute set and service entity categories.

IS-113 Added HSA-ID

---

ELN-0603 - Registry for Identifiers.md

Update ELN-0603 - Registry for Identifiers.md

---

ELN-0603 - Registry for Identifiers.md
ELN-0608 - Certificate Profile for Central Signing Services.md

Updates to allow inclusion of extended authentication information in AuthContextExtensions

Extensions of SAML Auth Context Ext

---

09 - DSS Extension for Federated Signing Services.md
versions.md

It is now possible to use pass several saml:AuthnContextClassRef elements.

IS-124 Updated CertRequestPropertiesType

---

03 - Registry for Identifiers.md

IS-147 Restrictions on eIDAS authn context classes

---

03 - Registry for Identifiers.md

IS-128 Added OID for SVT timestamp policy

---

02 - Deployment Profile for the Swedish eID Framework.md
13 - Signature Activation Protocol.md
versions.md

Update 13 - Signature Activation Protocol.md

---

README.md

IS-193 Restructured into authentication and signature sections

---

Identity Binding.md

Please se suggested updates for identity binding.

IS-199 Spec identity binding june 2023

---

Tekniska anslutningsregler.md

IS-201 Both public and private organizations can sign "eID för medarbetare"

---

Tekniska anslutningsregler.md

IS-204 Removed hard requirements for holder-of-key

---

06 - Entity Categories for the Swedish eID Framework.md
18 - User Message Extension in SAML Authentication Requests.md
README.md
versions.md

IS-195: Introduced the UserMessage AuthnRequest-extension

---

04 - Attribute Specification for the Swedish eID Framework.md

IS-208 Added note about scoped attributes

---

03 - Registry for Identifiers.md
04 - Attribute Specification for the Swedish eID Framework.md
06 - Entity Categories for the Swedish eID Framework.md
09 - DSS Extension for Federated Signing Services.md
14 - Principal Selection in SAML Authentication Requests.md

IS-206 Fixed broken URLs

---

03 - Registry for Identifiers.md

IS-221 Changed binding levels to process URI:s

---

03 - Registry for Identifiers.md
07 - Implementation Profile for using DSS in Central Signing Services.md

IS-184 Introduced new DSS error codes

---

OIDC - Sweden Connect - Claims and Scopes Specification.md

First draft of OIDC claims and scopes specification focusing on eIDAS attributes.
Closes #203

IS-203 OIDC claims and scopes

---

12 - BankID Profile for the Swedish eID Framework.md
docs/december-2024/index.html
docs/index.html

IS-229 Updates for latest BankID API version

---

Tekniska anslutningsregler.md

IS-232 Fixed broken links to external resources.

---

Tekniska anslutningsregler.md

IS-234 Changes for "auktorisationssystem"
